"""All cnstants used in theproject."""
import os
from pathlib import Path

API_KEY = os.getenv("UMLS_API_KEY")
BASE_URL = "https://download.nlm.nih.gov/"

UMLS_VERSION = "2023AA"
UMLS_SUFFIX = "umls/kss/{version}/umls-{version}-metathesaurus-level-0.zip"
UMLS_URL = BASE_URL + UMLS_SUFFIX


# https://download.nlm.nih.gov/umls/kss/2023AA/umls-2023AA-metathesaurus-level-0.zip
# RX_VERSION = "RxNorm_weekly_10052022"
# RX_SUFFIX = f"umls/kss/rxnorm/RxNorm_weekly_{RX_VERSION}&apiKey="
# SNOMED_CT_VERSION = "RF2_PRODUCTION_20220901T120000Z"
# SNOMED_CT_SUFFIX = f"mlb/utsauth/USExt/SnomedCT_USEdition{SNOMED_CT_VERSION}.zip&apiKey="

PACKAGE_DIR = Path(__file__).resolve().parent
DATA_DIR = PACKAGE_DIR / "data"
MAPPINGS_DIR = PACKAGE_DIR / "mappings"
MAPPINGS_FILE = "sssom.tsv"
UMLS_SSSOM_TSV = MAPPINGS_DIR / MAPPINGS_FILE

SUBJECT_ID = "subject_id"
OBJECT_ID = "object_id"
PREDICATE_ID = "predicate_id"
MAPPING_JUSTIFICATION = "mapping_justification"
MATCH_STRING = "match_string"
MAPPING_TOOL = "mapping_tool"
MAPPING_DATE = "mapping_date"

MRCONSO_COLUMN_HEADERS = [
    "CUI",  # Unique identifier for concept
    "LAT",  # Language of Terms(s)",
    "TS",  # Term Status",
    "LUI",  # Local Unique Identifier",
    "STT",  # String Type",
    "SUI",  # Unique Identifier for String",
    "ISPREF",  # Indicates whether AUI is preferred",
    "AUI",  # Unique identifier for atom",
    "SAUI",  # Source asserted atom identifier",
    "SCUI",  # Source asserted concept identifier",
    "SDUI",  # Source descriptor identifier",
    "SAB",  # source name",
    "TTY",  # Term Type in Source",
    "CODE",  # Unique Identifier or code for string in source
    "STR",  # String
    "SRL",  # Source Restriction Level
    "SUPPRESS",  # Suppressible Flag
    "CVF",  # Content View Flag
]

MRMAP_COLUMN_NAMES = [
    "MAPSETCUI",  # Unique identifier for the UMLS concept which represents the whole map set.
    "MAPSETSAB",  # Source abbreviation (SAB) for the provider of the map set.
    "MAPSUBSETID",  # Map subset identifier used to identify a subset of related mappings within a map set. This is used for cases where the FROMEXPR may have more than one potential mapping (optional).  # noqa
    "MAPRANK",  # Order in which mappings in a subset should be applied. Used only where MAPSUBSETID is used. (optional)
    "MAPID",  # Unique identifier for this individual mapping. Primary key of this table to identify a particular row.
    "MAPSID",  # Source asserted identifier for this mapping (optional).
    "FROMID",  # Identifier for the entity being mapped from. This is an internal UMLS identifier used to point to an external entity in a source vocabulary (represented by the FROMEXPR). When the source provides such an identifier, it is reused here. Otherwise, it is generated by NLM. The FROMID is only unique within a map set. It is not a pointer to UMLS entities like atoms or concepts. There is a one-to-one correlation between FROMID and a unique set of values in FROMSID, FROMEXPR, FROMTYPE, FROMRULE, and FROMRES within a map set.   # noqa
    "FROMSID",  # Source asserted identifier for the entity being mapped from (optional).
    "FROMEXPR",  # Entity being mapped from - can be a single code/identifier /concept name or a complex expression involving multiple codes/identifiers/concept names, Boolean operators and/or punctuation   # noqa
    "FROMTYPE",  # Type of entity being mapped from.
    "FROMRULE",  # Machine processable rule applicable to the entity being mapped from (optional)
    "FROMRES",  # Restriction applicable to the entity being mapped from (optional).
    "REL",  # Relationship of the entity being mapped from to the entity being mapped to.
    "RELA",  # Additional relationship label (optional).
    "TOID",  # Identifier for the entity being mapped to. This is an internal identifier used to point to an external entity in a source vocabulary (represented by the TOEXPR). When the source provides such an identifier, it is reused here. Otherwise, it is generated by NLM. The TOID is only unique within a map set. It is not a pointer to UMLS entities like atoms or concepts. There is a one-to-one correlation between TOID and a unique set of values in TOSID, TOEXPR, TOTYPE, TORULE, TORES within a map set.   # noqa
    "TOSID",  # Source asserted identifier for the entity being mapped to (optional).
    "TOEXPR",  # Entity being mapped to - can be a single code/identifier/concept name or a complex expression involving multiple codes/identifiers/concept names, Boolean operators and/or punctuation.   # noqa
    "TOTYPE",  # Type of entity being mapped to.
    "TORULE",  # Machine processable rule applicable to the entity being mapped to (optional).
    "TORES",  # Restriction applicable to the entity being mapped to (optional).
    "MAPRULE",  # Machine processable rule applicable to this mapping (optional).
    "MAPRES",  # Restriction applicable to this mapping (optional).
    "MAPTYPE",  # Type of mapping (optional).
    "MAPATN",  # The name of the attribute associated with this mapping [not yet in use]
    "MAPATV",  # The value of the attribute associated with this mapping [not yet in use]
    "CVF",  # The Content View Flag is a bit field used to indicate membership in a content view.
]
